Add allowsExternalPlayback Property for ios
TheWidlarzGroup/react-native-video pull request #1057
Opened 2018-06-08 03:16 UTC by genglei01

Make the video control can disable allowsExternalPlayback for ios

2018-06-08 05:48 UTC, cobarx requested changes
Looks great. Can you add an entry in the README for this prop.

2018-06-08 05:48 UTC, cobarx commented on ios/RCTVideo.m
> +      _allowsExternalPlayback = YES;
The indentation is off here.

2018-06-10 16:36 UTC, genglei01 commented
I have updated the README.

2018-06-10 17:55 UTC, cobarx approved these changes

2018-06-10 17:56 UTC, cobarx commented
Thanks for updating this!

2018-06-10 17:56 UTC, merged