Fix for isssue #1463
TheWidlarzGroup/react-native-video pull request #1466
Opened 2019-02-05 22:17 UTC by uioporqwerty

Fix for Issue, directly accessing NativeModules.UIManager is no longer supported.
Propose to add import to UIManager directly from 'react-native' module on top and change the code from NativeModules.UIManager.RCTVideo.~~~ to UIManager.getViewManagerConfig('RCTVideo').~~~ as suggested from react-native's warning.

2019-02-15 08:38 UTC, n1ru4l requested changes
@uioporqwerty Thank you for your contribution! Just one small change, afterwards I am going to merge this 😊

2019-02-15 08:38 UTC, n1ru4l commented on Video.js
> +      nativeResizeMode = UIManager.getViewManagerConfig('RCTVideo').Constants.ScaleToFill;
could you please move this a level higher?

**E.g.**
```js
let nativeResizeMode;
const RCTVideoInstance = UIManager.getViewManagerConfig('RCTVideo')

if (resizeMode === VideoResizeMode.stretch) {
    nativeResizeMode = RCTVideoInstance.Constants.ScaleToFill;
```

2019-02-18 11:17 UTC, closed without merging

2019-03-08 11:58 UTC, tapz commented
Is this already in npm?

2019-03-08 14:16 UTC, n1ru4l commented
Yes included in 4.4.0 https://www.npmjs.com/package/react-native-video