Feature/android media session
TheWidlarzGroup/react-native-video pull request #1780
Opened 2019-10-02 09:55 UTC by matejpolak

#### Describe the changes
Added mediaSession for Android ExoPlayer to let device know about currently used player. With this in place you can use some native features like pause/play using HW buttons on any compatible headset connected to the device, displaying playback buttons in PIP window (previous, play/pause, next), etc.. 

Currently using the simplest solution with usage of external ExoPlayer mediaSession extension library, which takes care of all needed mediaSession callback, and the session it self. To support more advanced features, full implementation may be needed. 

Since I'm not an Android expert, it's possible that some things, or additional metadata are missing. Please consider this as MVP which is currently implemented mainly to support PIP player controls. Feel free to suggest any change or pick deeper implementation if needed.

Also added `onExternalPauseToggled ` event prop, which notifies client about new play/pause state, so JS can perform needed actions based on this information.

2019-10-02 18:44 UTC, CHaNGeTe requested changes

2019-10-02 18:44 UTC, CHaNGeTe commented on android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
> +import com.google.android.exoplayer2.ui.PlayerControlView;
this import is duplicated

2019-10-02 18:55 UTC, CHaNGeTe commented on android-exoplayer/src/main/java/com/brentvatne/exoplayer/VideoEventEmitter.java
> +    void externalPauseTriggered(boolean isPlaying) {
the name of the func should'nt be toggled as well?

2019-10-05 04:55 UTC, CHaNGeTe approved these changes

2019-10-07 13:16 UTC, AurangzaibRamzan approved these changes

2020-09-07 12:38 UTC, rogerkerse commented
Hi, what is the state with this pull request? 😊 Would be very grateful if it got merged. We are using picture in picture on Android through another library, but since current version of react-native-video doesn't have media session, there are no playback buttons :(

2021-07-02 09:34 UTC, EyMaddis commented
Just a heads up if this ever gets merged:
`onExternalPauseToggled` is not necessary, there is already the prop `onPlaybackRateChange` that should be able to do the same. I just stumbled onto this PR, I did not test it.

2022-04-22 07:34 UTC, closed without merging