iOS Swift Conversion
TheWidlarzGroup/react-native-video pull request #2527
Opened 2021-11-04 08:17 UTC by nickfujita

This PR is a conversion of the iOS implementation from Objective-c to Swift.

Goals of conversion:
- Make the iOS codebase more accessible to developers coming from JS side to debug and contribute to the iOS side
- Cleanup codebase by utilizing more modern code patterns in Swift
- Prep codebase for unit tests by starting to modularize logic into smaller functions
- Improve code navigation by organize code into smaller files, grouping similar functions

During the conversion process some updates to the code structure were also made:
- Modularize codebase from single file to smaller focused files
- Untangled large nested IF statements
- Added more null checks, since Swift is more strict with null pointers
- Added property to allow for decoding of local video sources with self contained key for offline playback

Functionalify for my project's specific use cases were tested, but there are many other projects using other features or other combinations of features which still need to be tested. The hope is that this initial PR will help start the process for allowing other projects using this module to begin early testing and aide in validating the newly converted code.

If you have an existing project, please give this branch a try and reply with any issues, and will be happy to have a look.

2022-02-03 07:32 UTC, nickfujita commented
@zchwyng @sebjacobs @Fedeorlandau would you mind testing this in your existing project or any of the updated example project in this repo?

2022-02-03 15:16 UTC, Fedeorlandau commented
> @zchwyng @sebjacobs @Fedeorlandau would you mind testing this in your existing project or any of the updated example project in this repo?

Hi there, just raised it to the management team the need for us to start making PRs to the main repository as well and not only to our fork https://github.com/valtech-sd/react-native-video so we can get the latest fixes from you.
We've created a ticket in our internal tool to document all the features that we added and support the swift migration with the Dolby Atmos fix. Now it's up to the client to approve this and give us green light to update the PRs and stuff.

I'll let you know how it goes and thank you for you work here

2022-02-04 13:46 UTC, nickfujita commented
@Fedeorlandau that's great! was not even aware of the changes your team has been making in that branch. Excited to have a look through and see what we can get back into the main repo. 🙏🏼

2022-03-01 08:52 UTC, nickfujita commented
hey @Fedeorlandau wanted to check back in with you to see if you had some time to test out this PR?

2022-03-01 11:00 UTC, Fedeorlandau commented
> hey @Fedeorlandau wanted to check back in with you to see if you had some time to test out this PR?

Hi there. Not really, I'm not in the project anymore. @Adriandragdolby @ShaneMckenna23 could you please check this? Thanks

2022-03-11 01:50 UTC, nickfujita commented
Hi @adriandragdolby @ShaneMckenna23 would either of you be able to perform a test of this Swift conversion? The test application sin the project have been updates, so you can simply run the command `yarn xbuild ios` to quickly test the player

2022-04-20 07:59 UTC, hueniverse commented
@nickfujita I think v6 would be the right time to just go ahead and make the move! If we break stuff, we will get fresh report from the people who upgrade and test it out. Care to update the branch to current master?

2022-05-17 08:01 UTC, armadilio3 approved these changes

2022-05-17 08:01 UTC, armands-malejevs commented on ios/Video/Features/RCTPlayerObserver.swift
> +//        NotificationCenter.default.removeObserver(_handlers,
Maybe we can remove this if it is unused?

2022-05-17 12:51 UTC, freeboub commented on examples/basic/android/app/src/main/AndroidManifest.xml
> -      android:usesCleartextTraffic="true"
can you keep android:usesCleartextTraffic, it is usefull for testing !

2022-05-18 03:04 UTC, cobarx commented on examples/basic/android/app/proguard-rules.pro
> -# If your project uses WebView with JS, uncomment the following
Odd that we are removing all the rules. I doubt this matters much since it's not a production app.

2022-05-18 03:04 UTC, cobarx commented on examples/basic/android/app/_BUCK
> +# To learn about Buck see [Docs](https://buckbuild.com/).
Why is this getting renamed from `BUCK` to `_BUCK`

2022-05-18 03:04 UTC, cobarx commented on examples/basic/android/app/src/main/AndroidManifest.xml
> -      android:usesCleartextTraffic="true"
Agree on this, it's helpful to have http:// support

2022-05-18 03:04 UTC, cobarx commented on examples/basic/android/gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-6.7.1-all.zip
FWIW, this doesn't work on M1 Macs but 6.9.0 does

2022-05-18 03:04 UTC, cobarx commented on examples/basic/ios/VideoPlayer/main.m
> -/**
Why remove this header?

2022-05-18 04:31 UTC, nickfujita commented
@cobarx The example projects were recreated with a create react native app template, so some of the things were removed, such as comments, rules, etc. Added back the ones that were mentioned above.

2022-05-18 04:41 UTC, cobarx approved these changes

2022-05-18 21:58 UTC, freeboub requested changes

2022-05-18 21:58 UTC, freeboub commented on examples/basic/android/app/src/main/java/com/videoplayer/MainApplication.java
> -      return Arrays.asList(
OK I double check, the sample works correctly.

So the autolink seems to be done automatically with last react-native version.
can you just patch the README.md to indicate the change in following section ?

#### **MainApplication.java**

2022-05-19 02:28 UTC, nickfujita commented on examples/basic/android/app/src/main/java/com/videoplayer/MainApplication.java
> -      return Arrays.asList(
updated the readme

2022-05-19 05:31 UTC, freeboub approved these changes

2022-05-19 13:29 UTC, merged

2022-05-20 00:01 UTC, hueniverse commented
Fantastic work everyone! Thanks @nickfujita for sticking with it...