Improves ExoPlayer seek performance
TheWidlarzGroup/react-native-video pull request #2555
Opened 2021-12-11 16:31 UTC by vemarav

Currently, the seek takes nearly 2 seconds to finish on local files(file:///<path to file>) in android.

The default exoplayer SeekParamaters is EXACT. If we replace it with CLOSEST_SYNC the seek happens instantly with ±1 sec.

2022-04-23 12:01 UTC, freeboub commented
looks Googe for me, low risk

2022-04-23 18:29 UTC, hueniverse commented
@freeboub please submit an official review through GitHub. Click on the Files Changed tab and then Review and approve.

2022-04-23 18:51 UTC, freeboub approved these changes

2022-06-13 10:16 UTC, armadilio3 requested changes

2022-06-13 10:16 UTC, armands-malejevs commented on android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
> +                                .setSeekParameters(SeekParameters.CLOSEST_SYNC)
This could be a breaking change for some, can you make this into a prop where Exact is the default so that closest sync is an optional?

(I think that this might be an issue for SSAI streams where you need to snap exactly to the beginning or end of an ad, I haven't confirmed this but the change sounds like it could have an effect on this use case)

2022-06-23 20:43 UTC, hueniverse commented
Closing due to lack of response (from the original submitted or anyone else to review and rebase). If someone wants to pick this up please open a new PR that ports this code into the current master. We are doing our best to start clean with v6 which requires being a bit aggressive in closing stale PRs that are over a year old. Please don't consider this dismissing of your work and contribution - it's greatly appreciated.

2022-06-23 20:43 UTC, closed without merging