Fix/add pip config ios
TheWidlarzGroup/react-native-video pull request #2562
Opened 2021-12-20 21:19 UTC by g7i

#### Describe the changes
Add audio configs required for PIP for iOS

2021-12-21 06:06 UTC, g7i commented
Fixes: #2561

2022-02-03 07:35 UTC, nickfujita commented
@g7i would you mind testing this PR for the iOS conversion to swift? It does not have the changes you have made here, but I'd be happy to add them in afterwards. I'm looking to have anyone who has contributed to ios test out the converted version. Please be aware that there is a required update to add `use_frameworks! :linkage => :static` to your project Podfile
https://github.com/react-native-video/react-native-video/pull/2527

2022-02-21 15:26 UTC, keyberth-rengel commented
how's it going? Hey, how could you do picture-in-picture? I've been trying for many months but I haven't found any information. Could you help me?

2022-03-28 22:36 UTC, mattleff requested changes
This change should be guarded by an iOS version check

2022-03-28 22:36 UTC, mattleff commented on ios/Video/RCTVideo.m
> +    _pipController.canStartPictureInPictureAutomaticallyFromInline = true;
```suggestion
    if (@available(iOS 14.2, *)) {
        _pipController.canStartPictureInPictureAutomaticallyFromInline = true;
    }
```

2022-04-22 21:35 UTC, hueniverse commented
@g7i Thank you for the PR. Can you review @mattleff suggestion? Also, how can we test this change?

2022-04-26 21:21 UTC, freeboub commented
> @g7i Thank you for the PR. Can you review @mattleff suggestion? Also, how can we test this change?

It can be enabled by default in basic sample ;)

2022-04-26 21:21 UTC, freeboub commented
> @g7i Thank you for the PR. Can you review @mattleff suggestion? Also, how can we test this change?

It can be enabled by default in basic sample ;)

2022-06-23 20:39 UTC, hueniverse commented
Closing due to lack of response (from the original submitted or anyone else to review and rebase). If someone wants to pick this up please open a new PR that ports this code into the current master. We are doing our best to start clean with v6 which requires being a bit aggressive in closing stale PRs that are over a year old. Please don't consider this dismissing of your work and contribution - it's greatly appreciated.

2022-06-23 20:39 UTC, closed without merging