updated ReactVideoView.java to fix seeking issue on android
TheWidlarzGroup/react-native-video pull request #2712
Opened 2022-06-07 13:03 UTC by monahans

This PR fixes a bug when trying to seek in the Video component on Android. Before, the video would skip to the beginning of the video if the user tried to seek, but now it works as expected.

To test, simply use the video component on android, and you are now able to seek.

2022-06-07 20:44 UTC, freeboub commented
@monahans can you please use the constant ? "3" seems strange here, nobody will understand.
As sample there is already:  
https://github.com/react-native-video/react-native-video/pull/2555/files
https://github.com/react-native-video/react-native-video/pull/2511/files

2022-06-07 20:45 UTC, freeboub requested changes
please use enum / constant: SeekParameters.CLOSEST_SYNC I think

2022-06-08 15:53 UTC, monahans commented
Updated to use MediaPlayer.SEEK_CLOSEST

2022-06-09 17:06 UTC, freeboub approved these changes

2022-06-09 17:06 UTC, merged

2024-03-25 05:54 UTC, khushal87 commented
When will the PR be in the latest beta release?