feat: refactor resize prop handler
TheWidlarzGroup/react-native-video pull request #3286
Opened 2023-10-10 07:51 UTC by KrzysztofMoch

**This is internal change only**
## Summary
Map JS values to native equivalents and remove old exported values. With this we have clear type and same JS values for platforms

## Test Plan
- [x] `resize` prop work in example app

2023-10-10 20:31 UTC, freeboub requested changes

2023-10-10 20:31 UTC, freeboub commented on android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerViewManager.java
>      public @Nullable Map<String, Object> getExportedViewConstants() {
I think you can completely remove this function ?!

2023-10-10 20:31 UTC, freeboub commented on ios/Video/RCTVideoManager.swift
>      override func constantsToExport() -> [AnyHashable : Any]? {
same here can be completly removed ?

2023-10-10 20:31 UTC, freeboub commented on android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerViewManager.java
> +            default:
```suggestion
            case "none":
            case "contain":
                 videoView.setResizeModeModifier(ResizeMode.RESIZE_MODE_FIT);
                 break;
            default:
                 DebugLog.w(TAG, "unsupported resizeMode: '" +  resizeMode + "' apply 'fit' option")
                 videoView.setResizeModeModifier(ResizeMode.RESIZE_MODE_FIT);
                 break;
```

2023-10-11 07:14 UTC, KrzysztofMoch commented on android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerViewManager.java
>      public @Nullable Map<String, Object> getExportedViewConstants() {
Yes, Done ✅

2023-10-11 07:15 UTC, KrzysztofMoch commented on ios/Video/RCTVideoManager.swift
>      override func constantsToExport() -> [AnyHashable : Any]? {
Yes, Done ✅

2023-10-11 07:15 UTC, KrzysztofMoch commented on android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerViewManager.java
> +            default:
Done ✅

2023-10-11 19:56 UTC, freeboub approved these changes

2023-10-11 19:56 UTC, merged