feat: add release-it
TheWidlarzGroup/react-native-video pull request #3342
Opened 2023-11-08 22:41 UTC by freeboub

Integrate release-it tool for new release management

Next version can be generated with:
npx release-it --preRelease=alpha

should address: https://github.com/react-native-video/react-native-video/issues/3333

2023-11-09 02:55 UTC, evoactivity commented
I've been thinking about adding changesets here, it works a lot better for community projects as you don't have to enforce every PR to follow conventional commits, it makes keeping a changelog very simple as peoples changesets get added automatically. It can be completely automated through github actions so anyone with merge access on the repo will be able to make a release. Releases can goto github and npm.

https://github.com/changesets/changesets

I have a repo using automated changesets here if you would like to see how I have it setup
https://github.com/ektotv/playlist

2023-11-09 12:07 UTC, KrzysztofMoch commented
@evoactivity Thanks for your feedback! 
But I think that for us it will be much easier to use [release-it](https://github.com/release-it/release-it) with [changelog plugin](https://github.com/release-it/conventional-changelog). To enforce that every PR follow conventional commits we can use [github action](https://github.com/amannn/action-semantic-pull-request). We (I and @freeboub) have already used release-it so it will be easier for us to configurate and use it

2023-11-09 12:13 UTC, KrzysztofMoch commented on package.json
>      "files": [
we should make sure that next release won't have docs and example 😅
```suggestion
    "files": [
        ...
        "!docs",
        "!examples",
        ...
    ]
```

2023-11-09 12:17 UTC, KrzysztofMoch requested changes
update `package.json` to exclude `docs` and `examples` and we are ready to go

2023-11-09 21:27 UTC, freeboub commented
> we need update `package.json` to exclude `docs` and `examples` and we are ready to go

I added, but I think this is not mandatory, all the !XXX are subfolders of included folders.

2023-11-09 21:29 UTC, freeboub commented
> I've been thinking about adding changesets here, it works a lot better for community projects as you don't have to enforce every PR to follow conventional commits, it makes keeping a changelog very simple as peoples changesets get added automatically. It can be completely automated through github actions so anyone with merge access on the repo will be able to make a release. Releases can goto github and npm.
> 
> https://github.com/changesets/changesets
> 
> I have a repo using automated changesets here if you would like to see how I have it setup https://github.com/ektotv/playlist

Thank you for the clue, I agree it would be interesting to have github integration, but I had this release-it integration under the hand, it was very easy.

2023-11-10 07:20 UTC, KrzysztofMoch approved these changes
LGTM 👍

2023-11-13 20:35 UTC, merged