fix: Fix types for `ReactVideoSource` to also allow `require(..)` sources
TheWidlarzGroup/react-native-video pull request #3354
Opened 2023-11-16 16:34 UTC by mrousavy

We need to be careful here to not use `any`, so I used `NodeRequire` - which is afaik present in all React Native environments as a type.

2023-11-16 17:32 UTC, freeboub commented on CHANGELOG.md
> +- Fix types for ReactVideoSource to also allow require(..) sources
you can remove this change for now, I will fix PR template, but thank for it 🙏

2023-11-16 17:35 UTC, freeboub commented
This Pr doesn't pass the linter step.
you can check locally with "yarn lint" command.
Can you please check ?

notice that ideally we should move require option inside uri prop, but that is another subject !

2023-11-16 17:36 UTC, freeboub requested changes

2023-11-16 17:36 UTC, freeboub commented on CHANGELOG.md
> +- Fix types for ReactVideoSource to also allow require(..) sources
```suggestion
```

2023-11-16 17:36 UTC, freeboub commented on CHANGELOG.md
> +
```suggestion
```

2023-11-17 13:52 UTC, mrousavy commented
Oh my bad I only checked typescript output - will fix linting now!

2023-11-18 13:30 UTC, freeboub commented
@mrousavy I rework the fix here: https://github.com/react-native-video/react-native-video/pull/3361/files can you please check if it works for you ?
Thank you

2023-11-18 14:40 UTC, closed without merging

2023-11-18 14:40 UTC, freeboub commented
My Pr has been merged, don't hesitate to comment on it if you see any issues with it !
Thank you !