chore(sample): fix lint and ts sample
TheWidlarzGroup/react-native-video pull request #3365
Opened 2023-11-20 13:53 UTC by freeboub

start fix eslint and tsc warnings in the sample

2023-11-23 07:00 UTC, KrzysztofMoch requested changes

2023-11-23 07:00 UTC, KrzysztofMoch commented on examples/basic/package.json
I thought that i remove `react-native-video` in #3353. (to remove dep loop, i used manual linking)

2023-11-23 07:00 UTC, KrzysztofMoch commented on examples/basic/android/app/src/main/java/com/videoplayer/MainApplication.java
> -          packages.add(new ReactVideoPackage());
This one should be there for manual linking (see #3353)

2023-11-23 07:00 UTC, KrzysztofMoch commented on examples/basic/package.json
Please remove it, i seems like my mistake

2023-11-27 21:22 UTC, freeboub commented
@KrzysztofMoch I backport your CI changes to be able to build the sample in this (Thank you again for that).
I want to enhance it be able to build with different build option (with or without ads typically).
What do you advise ? copy build-<platform>.yml to build-<platform>-withads.yml or directly patch the file with something like:
        run: cd examples/basic/android && ./gradlew assembleDebug --build-cache  && ./gradlew clean && export ENABLE_ADS=true && ./gradlew assembleDebug --build-cache && cd ../../..

2023-11-27 21:24 UTC, freeboub commented
tI don't understand why I don't see my initial changes /o\

2023-11-27 21:26 UTC, KrzysztofMoch commented
> @KrzysztofMoch I backport your CI changes to be able to build the sample in this (Thank you again for that).
> 
> I want to enhance it be able to build with different build option (with or without ads typically).
> 
> What do you advise ? copy build-<platform>.yml to build-<platform>-withads.yml or directly patch the file with something like:
> 
>         run: cd examples/basic/android && ./gradlew assembleDebug --build-cache  && ./gradlew clean && export ENABLE_ADS=true && ./gradlew assembleDebug --build-cache && cd ../../..

You can create separate "job" in build file so we will have build for Ads and build with non ads

2023-11-30 07:27 UTC, KrzysztofMoch approved these changes
LGTM 👍

2023-11-30 20:17 UTC, merged