chore: lint project
TheWidlarzGroup/react-native-video pull request #3395
Opened 2023-12-02 16:50 UTC by KrzysztofMoch

## Summary
Lint and format code (all changes are made by linters, there is no manual changes)

## Testplan
- [ ] should pass tests

2023-12-03 14:13 UTC, KrzysztofMoch commented
Nice, all green ✅ @freeboub @YangJonghun

2023-12-03 14:21 UTC, freeboub commented
It would be better if you move back indent to 4 spaces, here we are loosing all the history :/

2023-12-03 15:42 UTC, YangJonghun commented
@KrzysztofMoch
Looks good to me. I'd also suggest using Spotless, although it's not required.

2023-12-06 19:16 UTC, KrzysztofMoch commented
> It would be better if you move back indent to 4 spaces, here we are loosing all the history :/

Done ✅

2023-12-06 19:19 UTC, KrzysztofMoch commented
> @KrzysztofMoch Looks good to me. I'd also suggest using Spotless, although it's not required.

Thanks for suggestion 🙌, it looks good. But Spotless does not support swift, so implementing it only for android is not worth it IMO (Unless I haven't read about what useful magic feature ✨)

2023-12-06 20:27 UTC, freeboub requested changes

2023-12-06 20:27 UTC, freeboub commented on android/src/main/java/com/brentvatne/common/API/SubtitleStyle.kt
> +package com.brentvatne.common.api
It makes sense, but I think you should also rename the folder ?
I think a simple git mv would fix this

2023-12-06 20:27 UTC, freeboub commented on ios/Video/Features/RCTIMAAdsManager.swift
> -import Foundation
This change is not very good ... Do you think there is a way to avoid that ?
This is not a blocking point !

2023-12-06 20:31 UTC, KrzysztofMoch commented on android/src/main/java/com/brentvatne/common/API/SubtitleStyle.kt
> +package com.brentvatne.common.api
agree, I missed that

2023-12-06 20:59 UTC, KrzysztofMoch commented on android/src/main/java/com/brentvatne/common/API/SubtitleStyle.kt
> +package com.brentvatne.common.api
Done ✅

2023-12-07 07:40 UTC, freeboub approved these changes

2023-12-07 07:47 UTC, merged