feat!: move require (local files) to `source.uri`
TheWidlarzGroup/react-native-video pull request #3535
Opened 2024-02-14 14:50 UTC by KrzysztofMoch

## Summary
From now "local files" that are imported via `require` will be passed in `source.uri`

### Motivation
This will unblock video config for local files

### Changes
changed `resolveAssetSourceForVideo` function (JS side change only) 

## Test plan
- [x] Tested in example app

2024-02-15 22:00 UTC, freeboub requested changes
No change on native side ?
Can you also update the sample to be able to test easily ? 
I would also expect a documentation update !

2024-02-16 11:35 UTC, KrzysztofMoch commented on src/utils.ts
> +
@freeboub In stand of making breaking change I will leave old option and add reference in docs to use new way. With this we won't have to make breaking change

> No native side change ?

Yes as you can see, we earlier converted `require` into `{ uri: "some uri to local file" }` so basically I've just added one if statement

2024-03-12 21:22 UTC, freeboub commented
@KrzysztofMoch finally successfully tested ! :)
what do you think of this addtionnal commit ? https://github.com/react-native-video/react-native-video/pull/3584/commits/9ab8712e12eab084a56c7640d9c49fc91dd597d7

2024-03-12 21:37 UTC, freeboub approved these changes

2024-03-13 07:23 UTC, KrzysztofMoch commented
> what do you think of this addtionnal commit ? https://github.com/react-native-video/react-native-video/commit/9ab8712e12eab084a56c7640d9c49fc91dd597d7

Good idea, I have added this

2024-03-13 07:23 UTC, merged