fix(ios): Do not crash when accessLog return nil
TheWidlarzGroup/react-native-video pull request #3549
Opened 2024-02-27 21:26 UTC by gkueny

## Summary

accessLog method can return nil if no logging information are currently available (see https://developer.apple.com/documentation/avfoundation/avplayeritem/1388499-accesslog).

### Motivation

should fix https://github.com/react-native-video/react-native-video/issues/3424

### Changes

I handle the case where `accessLog` return `nil` & do not call onVideoBandwidthUpdate if it's `nil`. That should avoid some crash.

## Test plan

Sadly I can not reproduce the crash. So I do not have a real test plan unless a minimal reproduction is given.

2024-02-28 08:28 UTC, douzal34 commented
I have tested his branch and my issue from #3424 is not freezing anymore.
Great job @gkueny !

2024-02-28 09:16 UTC, KrzysztofMoch requested changes
Thank you! I left one small comment, but it looks good

2024-02-28 09:16 UTC, KrzysztofMoch commented on ios/Video/RCTVideo.swift
> +        }
Let's make this more elegant:
```swift
    @objc
    func handleAVPlayerAccess(notification: NSNotification!) {
        guard let accessLog = (notification.object as? AVPlayerItem)?.accessLog() else {
            return
        }

        guard let lastEvent = accessLog.events.last else { return }
        onVideoBandwidthUpdate?(["bitrate": lastEvent.observedBitrate, "target": reactTag])
    }
  ```

2024-02-28 09:43 UTC, gkueny commented
@KrzysztofMoch thanks for the review.

> I did not find a way to trigger onVideoBandwidthUpdate. Someone maybe can point me a way to reproduce this beahavior ?

For my own knowledge, do you know how a can trigger `AVPlayerItemNewAccessLogEntry` notification ?

2024-02-28 22:12 UTC, freeboub approved these changes

2024-02-29 13:39 UTC, KrzysztofMoch approved these changes
@gkueny I am not sure... 😅 - it's sometimes just work for me

2024-02-29 13:40 UTC, merged