Feat(android): implement asset folder playback
TheWidlarzGroup/react-native-video pull request #3733
Opened 2024-05-04 12:05 UTC by freeboub

## Summary
Feature: implement playback ability from app asset folder

### Motivation
Fix: https://github.com/react-native-video/react-native-video/issues/2825

### Changes
- remove some used functions
- Implement playback with DataSource.Factory from asset

## Test plan
- sample video asset added in the sample app

2024-05-04 12:05 UTC, freeboub commented
And thank you @evoactivity for the link !

2024-05-05 21:52 UTC, KrzysztofMoch requested changes

2024-05-05 21:52 UTC, KrzysztofMoch commented on android/src/main/assets/broadchurch.mp4
This should be here ?! it will increase app size by 3.20MB - I think this should be moved to basic example folder

2024-05-06 19:45 UTC, freeboub commented on android/src/main/assets/broadchurch.mp4
Very good catch, thank you very much !
I have just move it to sample folder

2024-05-06 19:46 UTC, KrzysztofMoch approved these changes
LGTM 🙌

2024-05-06 19:51 UTC, merged