perf: ensure we do not provide callback to native if no callback provided from app
TheWidlarzGroup/react-native-video pull request #3735
Opened 2024-05-05 19:11 UTC by freeboub

## Summary
As discussed with @KrzysztofMoch a possible optimization is to avoid giving callback functions (starting with 'on*') to native if application didn't provide it 

### Motivation
performances improvements.
Additionnally, we must keep the useCallback as paramters of the function are differents between native & applicative, for exemple:
```TS
    const _onTimedMetadata = useCallback(
      (e: NativeSyntheticEvent<OnTimedMetadataData>) => {
        onTimedMetadata?.(e.nativeEvent);
      },
      [onTimedMetadata],
    );
````
send e.nativeEvent to application

### Changes
Just add ternary to check to avoid giving the callback to native

## Test plan
Basic tests done on android/ios with the sample

2024-05-05 19:22 UTC, KrzysztofMoch commented
I also think we should do "early returns" - because we don't need to load tracks data if user don't revive it

I will send you patch for iOS later

2024-05-05 19:30 UTC, KrzysztofMoch requested changes
We need to add "or" condition to places that "poster" logic depends on

like 
```
onVideoLoad={
            onLoad || hasPoster
              ? (onVideoLoad as (e: NativeSyntheticEvent<object>) => void)
              : undefined
          }
```

2024-05-05 19:30 UTC, KrzysztofMoch commented on src/Video.tsx
> +          }
We want to also have this callback when `hasPoster` is `true`

2024-05-05 19:30 UTC, KrzysztofMoch commented on src/Video.tsx
> +          onVideoLoadStart={onLoadStart ? onVideoLoadStart : undefined}
Same - We want to also have this callback when `hasPoster` is true

2024-05-06 20:33 UTC, freeboub commented
Good catch agin, thank you !
I integrate some of the swift fix you proposed to me also ! (but not all)

2024-05-06 20:48 UTC, KrzysztofMoch approved these changes
Nice let's merge this - I will make PR for "early returns" tomorrow

2024-05-07 09:06 UTC, merged