feat: add getCurrentPosition to component's ref
TheWidlarzGroup/react-native-video pull request #3824
Opened 2024-05-23 09:11 UTC by seyedmostafahasani

## Summary
This function retrieves and returns the precise current position of the video playback, measured in seconds.

### Motivation
The goal is to provide users with the ability to access the current position of the video playback. This allows for the creation of custom controls like forward and rewind buttons, enhancing user experience.

### Changes
A new function `getCurrentPosition` has been added to the component's ref.

## Test plan

2024-05-23 09:51 UTC, freeboub commented
Looks good to me, Just one note, I would prefer having the time in msec instead of sec. @KrzysztofMoch @YangJonghun what do you think of this point ?

2024-05-23 09:52 UTC, freeboub commented on android/src/main/java/com/brentvatne/react/VideoManagerModule.kt
> +           it?.getCurrentPosition(promise)
```suggestion
            it?.getCurrentPosition(promise)
```

2024-05-23 11:42 UTC, YangJonghun commented
As far as I know, `onProgress` callback exists for the same reason. I wonder for what purpose this method was implemented.

2024-05-23 14:43 UTC, seyedmostafahasani commented
@YangJonghun  you're correct! In situations where the user only needs to get the current position when interacting with custom controls, such as the rewind and forward buttons, it's not necessary to use a callback function that is called every progress update interval.

Instead, the user can use this approach that is only called when the user clicks the rewind or forward buttons. When a button is clicked, you can get the current position and then seek forward or backward based on the button that was clicked.

2024-05-23 14:51 UTC, YangJonghun commented
@seyedmostafahasani 
That makes sense!
However, I think it might be a bit difficult to use it for precise work due to the limitations of old architecture, since the current time value keeps changing on playback.
It will be great later when we're done with the new architecture :)
Thanks for your explanation.👍

2024-05-23 16:01 UTC, seyedmostafahasani commented
So now what is your opinion about the response of this function, second or millisecond?

2024-05-23 16:22 UTC, YangJonghun commented
@seyedmostafahasani 
Oh sorry to late response.
I like second(specifically, second as a float value).
I prefer the same format as the value returned by `onProgress`, and I think many developers will be familiar with the web's video.currentTime format

2024-05-23 16:53 UTC, seyedmostafahasani commented
I completely agree with you about second.

2024-05-23 19:26 UTC, freeboub commented
As C developer I prefer working with integer, but if you are ok for sec, then OK for me !

2024-05-23 19:27 UTC, freeboub commented on android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
> +            promise.resolve((double) currentPosition);
Directly use double here, if you cast to long, your will loose msec information !

```suggestion
            double currentPosition = player.getCurrentPosition() / 1000;
            promise.resolve(currentPosition);
```

2024-05-23 19:29 UTC, freeboub requested changes
See my comment for android

2024-05-23 22:12 UTC, freeboub approved these changes

2024-05-28 07:25 UTC, freeboub commented on docs/pages/component/methods.mdx
> +This function retrieves and returns the precise current position of the video playback, measured in seconds.
```suggestion
This function retrieves and returns the precise current position of the video playback, measured in seconds.
This function will throw an error if player is not initialized.
```

2024-05-28 07:28 UTC, freeboub requested changes

2024-05-28 07:28 UTC, freeboub commented on ios/Video/RCTVideo.swift
> +        resolve(currentTime)
it would be great to match android behavior: if playerItem is nil, reject the promise.

2024-05-28 08:17 UTC, freeboub approved these changes

2024-05-28 09:00 UTC, freeboub approved these changes

2024-05-28 09:00 UTC, merged

2024-06-28 12:29 UTC, YangJonghun commented
@freeboub @KrzysztofMoch @seyedmostafahasani 
I think we need to deprecate this feature
ref command with return value not supported by Fabric
(`save` command also have same problem)

2024-06-28 20:12 UTC, seyedmostafahasani commented
@YangJonghun I think we can use them with Fabric, but an important point is that these are deprecated methods on the native or JS side. Utilizing deprecated methods on the native or JS side may result in these functions not working correctly. I recommend checking out `react-native-blurhash`, as it employs Fabric. This library uses functions that return values via promises, such as the encode function, which you can observe in these URLs.
https://github.com/mrousavy/react-native-blurhash/blob/master/src/index.tsx
https://github.com/mrousavy/react-native-blurhash/blob/master/android/src/main/java/com/mrousavy/blurhash/BlurhashModule.kt

2024-06-29 03:17 UTC, YangJonghun commented
@seyedmostafahasani 
BlurHash is NativeModule.
TurboModule and Fabric are different. TurboModule can be return values
What I meant was that it's not possible to use a View as a ref and return it.

Currently we use `save` or `getCurrentPosition` in react-native-video is to reference a reactTag in NativeModule(VideoManager).
We are using `findNodeHandle` for above behavior, but findNodeHandle will be deprecated, so it is not recommended to continue using this method. We need to migrate to command method to replace it.
However command does not support return or callback functions.

2024-06-29 06:53 UTC, seyedmostafahasani commented
@YangJonghun Oh yes, you're right. Thanks for the detailed explanation. I was referring to the deprecated method `findNodeHandle`. Could you please take a look at the `react-native-view-shot` library? I think this library could help us.

2024-06-29 07:11 UTC, YangJonghun commented
@seyedmostafahasani 
Thanks for give me reference
But unfortunately react-native-view-shot also using `findNodeHandle` now. ([link](https://github.com/gre/react-native-view-shot/blob/master/src/index.js#L128))🥲

I guess I'll have to keep it for now and find a tricky way around it. Because we don't know when RN team get rid of findNodeHandle.
fyi) https://github.com/reactwg/react-native-new-architecture/blob/main/docs/enable-libraries-prerequisites.md

2024-06-29 07:27 UTC, seyedmostafahasani commented
@YangJonghun anytime!
Did you see this [PR](https://github.com/gre/react-native-view-shot/pull/516)

I agree with you, we can keep it for now. Also, if I find a better solution, I will share it with you.