chore: add setFullScreen to component's ref and remove presentFullscreenPlayer & dismissFullscreenPlayer
TheWidlarzGroup/react-native-video pull request #3855
Opened 2024-05-29 21:28 UTC by seyedmostafahasani

…eenPlayer & dismissFullscreenPlayer

## Summary
I added `setFullScreen` to handle fullScreen mode without controls.

### Motivation
The user can use it to handle fullscreen mode with custom controls, specifically refactoring the codebase and fix this [issue].(https://github.com/TheWidlarzGroup/react-native-video/issues/3732)

### Changes
I added a function called `setFullScreen` and removed the functions `presentFullscreenPlayer` and `dismissFullscreenPlayer`.

## Test plan

2024-05-30 06:56 UTC, freeboub requested changes
We cannot remove existing APIs on 6.X branch, I don't understand why you need this change. Can you please clarify ?

2024-05-30 09:10 UTC, seyedmostafahasani commented
I think we can implement full-screen mode with just this function. We don't need two functions to handle it. Additionally, if we remove these functions, we will eliminate an unnecessary useState from the video component, which prevents re-rendering. Specifically, we will also fix another issue in the library, #3732. The main point is that we handle this logic with just one function. What is your opinion?

2024-05-30 15:21 UTC, seyedmostafahasani commented
@freeboub what do you think about my points?

2024-05-31 21:28 UTC, freeboub commented
@seyedmostafahasani We cannot change api on V6.X, if we integrate such api change, we will need to bump to V7 and all apps using the package will have to upgrade their integration. as the team have a lot of api changes in mind, we try to keep api interoperability as much as possible.

Here is a sample: 
https://github.com/TheWidlarzGroup/react-native-video/pull/3867/files#diff-e2131d0631cdc1ddf0ba36827a27b86adf8e5b8ed162a280a53c6219f4df5a5f

I just move few props from the root of video to the source object, to avoid upgrade issue, I comment in doc that the old api is deprecated, and point to the new way to proceed.

It will allow easy upgrade for apps, we keep in mind that old api (deprecated) can be removed on V7.
Can you please do the same thing please ?
I think merging the 2 apis make sense, but we need to keep compatibility of old api some time

2024-05-31 21:29 UTC, freeboub requested changes

2024-05-31 21:29 UTC, freeboub commented on android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
> -                if (isFullscreen && fullScreenPlayerView != null && !fullScreenPlayerView.isShowing()) {
why did you remove this section ?
Please check git history, but I think it was fixing a problem !

2024-06-01 06:44 UTC, seyedmostafahasani commented
> @seyedmostafahasani We cannot change api on V6.X, if we integrate such api change, we will need to bump to V7 and all apps using the package will have to upgrade their integration. as the team have a lot of api changes in mind, we try to keep api interoperability as much as possible.
> 
> Here is a sample: https://github.com/TheWidlarzGroup/react-native-video/pull/3867/files#diff-e2131d0631cdc1ddf0ba36827a27b86adf8e5b8ed162a280a53c6219f4df5a5f
> 
> I just move few props from the root of video to the source object, to avoid upgrade issue, I comment in doc that the old api is deprecated, and point to the new way to proceed.
> 
> It will allow easy upgrade for apps, we keep in mind that old api (deprecated) can be removed on V7. Can you please do the same thing please ? I think merging the 2 apis make sense, but we need to keep compatibility of old api some time

I completely agree with you about deprecating the old API and planning to remove it in V7. I will add deprecation notices for both `presentFullscreenPlayer` and `dismissFullscreenPlayer`. This approach ensures backward compatibility while allowing a smooth transition for users until V7, where we can fully remove the old API.

2024-06-01 08:58 UTC, freeboub commented on android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
> -            if (controls && fullScreenPlayerView != null) {
not sure why you did that, but in the absolute, it makes sense.
BTW, I think this "control" test is not here as if controls == false, fullScreenPlayerView shall also be null

2024-06-01 08:58 UTC, freeboub commented on docs/pages/component/methods.mdx
> -### `pause`
I don't understand why you move pause, It is the first one in alphabetical order !

2024-06-02 14:09 UTC, freeboub commented
@seyedmostafahasani Thank you for the fix,
last remaining point, can you please remove deprecated functions in the sample please ? :)

following code shall be simplified:
 
```javascript
  toggleDecoration() {
    this.setState({decoration: !this.state.decoration});
    if (this.state.decoration) {
      this.video?.dismissFullscreenPlayer();
    } else {
      this.video?.presentFullscreenPlayer();
    }
  }
```

2024-06-02 14:10 UTC, freeboub requested changes

2024-06-02 14:10 UTC, freeboub commented on docs/pages/component/methods.mdx
> +### `setFullScreen`
There is an ordering issue here !

2024-06-02 18:40 UTC, seyedmostafahasani commented
@freeboub I removed the controls condition in the `updateFullScreenButtonVisibility` function. When the user sets `controls={false}`, the fullScreen button disappears in fullScreen mode, requiring the user to press the physical back button to exit fullScreen mode, which may cause confusion. What is your opinion?

2024-06-02 19:58 UTC, freeboub commented on examples/basic/src/VideoPlayer.tsx
>      if (this.state.decoration) {
this.video?.setFullScreen(!this.state.decoration);
would be cleaner! The goal is to remove lines here :)

2024-06-09 12:41 UTC, YangJonghun commented
I don't use native controls and fullscreen in this library, but I'm not sure if this breaking change is really necessary in this library.
It's not a duplicate function, so it doesn't have much effect on user DX as long as user pass an argument. Also, It's easy to remove useState and keep the existing API, so why we make breaking change?

2024-06-09 12:53 UTC, freeboub commented
It is not a breaking change as previous api are still working! It is just a preparation for api clean up ! (Let say for V7)

2024-06-09 13:19 UTC, YangJonghun commented
@freeboub 
oh..then I misunderstood.
(If possible, it would be nice to have something like a new-arch only prop that works synchronously. `ref.fullscreen = true`)

2024-06-09 14:51 UTC, freeboub commented
Yes I agree, Fullscreen management is one of the next challenge I think...

2024-06-10 06:49 UTC, KrzysztofMoch approved these changes
LGTM

2024-06-10 20:40 UTC, freeboub approved these changes

2024-06-10 20:41 UTC, merged