refactor: basic example from class component to functional component
TheWidlarzGroup/react-native-video pull request #3934
Opened 2024-06-23 20:12 UTC by seyedmostafahasani

## Summary
Refactor basic example from class component to functional component.

### Motivation
Fix some TypeScript issues and improve the readability of the functional component compared to the class component.

### Changes

## Test plan

2024-06-24 04:57 UTC, freeboub commented on examples/basic/src/utils/Toast.ts
> +import {Alert, ToastAndroid} from 'react-native';
I think this file should go into components folder

2024-06-24 05:09 UTC, freeboub requested changes
I added a small comment about Toast file but except this, changes looks good to me.
In a more general consideration:
- I don't think the split of overlay really bring interesting thing, but it goes in the good way
- please try to do smaller PR, it is really easier to review
- the global state also need to be removed/reworked. but let's keep it for later, there are enough changes in this PR

Please move Toast.ts and I will approve

2024-06-24 05:58 UTC, seyedmostafahasani commented
Sorry about the big PR. I wanted to do it in some small PRs, but all of them were related to each other, so I decided to combine them into this PR. I agree with you about the benefits of small PRs 🤝.

2024-06-24 07:30 UTC, freeboub approved these changes

2024-06-24 08:04 UTC, freeboub approved these changes

2024-06-27 12:44 UTC, KrzysztofMoch commented
@seyedmostafahasani seekbar is not working for me (on iOS)
And Btw local file (first source in example) is not loading for me, I have warning that I am try to load empty source - It's me or example broke somewhere ?

2024-06-27 12:49 UTC, freeboub commented
@KrzysztofMoch I think broken local videos issue comes from expo PR... Sometimes it works, sometimes not 🤨

2024-06-27 13:41 UTC, seyedmostafahasani commented
@KrzysztofMoch I saw your comments when I was refactoring. I tested on the master branch just to be on the safe side, and I noticed we have these issues. I think like @freeboub.

2024-06-27 13:44 UTC, KrzysztofMoch commented
Seekbar is not working on master ? 👀

2024-06-27 13:50 UTC, seyedmostafahasani commented
Yeah. It's not working correctly. Please see the video below.

https://github.com/TheWidlarzGroup/react-native-video/assets/3009224/903a4350-de42-4e05-a68e-2bcca8bf5ba9

2024-06-27 13:52 UTC, KrzysztofMoch commented
> Yeah. It's not working correctly. Please see the video below.
> 
>  Screen.Recording.2024-06-27.at.17.17.19.mov

This is actually working - it is just live source. I have issue with normal video, seekbar is not updating it's position (it's staying in one position)

2024-06-27 13:59 UTC, seyedmostafahasani commented
Yeah, you're right. Let me check it out on iOS first on the master branch, then I will test it on this PR.

2024-06-27 15:04 UTC, seyedmostafahasani commented
@KrzysztofMoch It's fixed. We need to refactor the state variable in another PR in the future.

2024-06-28 09:30 UTC, KrzysztofMoch approved these changes
Thanks, now it's working

2024-06-28 09:33 UTC, merged

2024-06-28 13:01 UTC, seyedmostafahasani commented
@KrzysztofMoch thanks for testing again!