chore: update method document
TheWidlarzGroup/react-native-video pull request #4072
Opened 2024-08-09 12:56 UTC by seyedmostafahasani

## Summary
Removed the `play` method from the method document.

### Motivation
To clean up the document.

### Changes

## Test plan

2024-08-09 13:01 UTC, moskalakamil commented on docs/pages/component/methods.mdx
> -  videoRef.current.play();
maybe we should add a resume method here (videoRef.current.resume)? and then update comment to // pause or resume the video

2024-08-09 13:13 UTC, moskalakamil requested changes

2024-08-09 13:13 UTC, moskalakamil commented on docs/pages/component/methods.mdx
> +  // pause the video
The other methods examples are connected - eg. 
```tsx
  // present or dismiss fullscreen player
  videoRef.current.presentFullscreenPlayer();
  videoRef.current.dismissFullscreenPlayer();
  ```
  So I think that we also should connect those methods into one comment, so 
  ```tsx
  // pause or resume the video
  videoRef.current.pause();
  videoRef.current.resume();
```

2024-08-09 13:14 UTC, moskalakamil commented
Thanks for PR!

2024-08-09 13:17 UTC, moskalakamil approved these changes

2024-08-12 11:55 UTC, KrzysztofMoch approved these changes

2024-08-12 11:55 UTC, merged