refactor(android): migrate DashUtil to Kotlin
TheWidlarzGroup/react-native-video pull request #4077
Opened 2024-08-11 19:33 UTC by seyedmostafahasani

## Summary
Migrate DashUtil to Kotlin

### Motivation
Migrate the codebase from Java to Kotlin

### Changes

## Test plan

2024-08-11 20:12 UTC, freeboub requested changes

2024-08-11 20:12 UTC, freeboub commented on android/src/main/java/androidx/media3/exoplayer/dash/DashUtil.kt
> +        TODO("Implement the logic to load and return the DashManifest")
This is a stub file, you don't need the todo ...

2024-08-12 05:56 UTC, freeboub approved these changes

2024-08-12 11:26 UTC, KrzysztofMoch approved these changes

2024-08-21 14:03 UTC, seyedmostafahasani commented
We have an issue excluding the Kotlin file in build.gradle.Please don’t merge this PR until it is fixed

2025-01-25 12:09 UTC, closed without merging

2025-01-25 12:09 UTC, freeboub commented
We should remove stub support by using reflexivity. let's close this PR