feat(android): supporting for hiding Exoplayer duration on android
TheWidlarzGroup/react-native-video pull request #4090
Opened 2024-08-15 07:41 UTC by ashlyWeiting

## Summary
This PR adds support for hiding the duration on Android devices.

### Changes
  -  Implemented a new prop to hide the duration on Android.
  -  Updated relevant Android-specific components to respect the new prop.
  - 
## Test plan
    1. Apply the new prop hideDuration = true to hide the duration.
    2. Verify that the video player does not display the duration when the prop is true.

2024-08-15 08:40 UTC, seyedmostafahasani commented
@ashlyWeiting 
I don't understand why we need this PR. In particular, when the user hides the seek bar, it indicates that the video is live, so we hide both the seek bar and the duration. However, if the user only wants to hide the duration, it might cause confusion.
Why would the user need to hide the duration?

2024-08-16 05:36 UTC, ashlyWeiting commented
I know this request is unusual, but over 10 Android users of my product have asked for it. Users think seeing the current position is sufficient. 
If you think this PR is unnecessary, I will close it.

Thank you for taking time to review my pull request!

2024-08-16 07:40 UTC, seyedmostafahasani commented
@freeboub @KrzysztofMoch 
WDYT?

2024-08-16 09:38 UTC, freeboub commented
I think this is not up to rnv to choose UI requirements. Btw, the pr is clean and easy to maintain, so ok for me !

2024-08-16 09:40 UTC, freeboub requested changes
I just think there is a missing typescript change in the component file. Can you double check please?

2024-08-16 10:06 UTC, seyedmostafahasani commented
@ashlyWeiting 
Please add the missing TypeScript to this file `src/specs/VideoNativeComponent.ts`

```
type ControlsStyles = Readonly<{
  hideSeekBar?: boolean;
  hideDuration?: boolean;
  seekIncrementMS?: Int32;
}>;
```

2024-08-16 10:07 UTC, seyedmostafahasani commented on src/types/video.ts
> +  hideDuration?: boolean;
Please add the missing TypeScript to this file `src/specs/VideoNativeComponent.ts`
```
type ControlsStyles = Readonly<{
  hideSeekBar?: boolean;
  hideDuration?: boolean;
  seekIncrementMS?: Int32;
}>;
```

2024-08-16 10:09 UTC, seyedmostafahasani commented
@ashlyWeiting 
Please update the document accordingly.

2024-08-17 06:02 UTC, ashlyWeiting commented
Thanks for the review! I've made the updates the document. Could you please take a look and let me know if everything looks good?

2024-08-17 07:35 UTC, freeboub approved these changes

2024-08-17 07:49 UTC, seyedmostafahasani approved these changes

2024-08-20 03:46 UTC, seyedmostafahasani commented
@KrzysztofMoch 
I think it's better to update the commit as shown below.
`feat(android): add support for hiding video duration`

WDYT?

2024-08-21 08:05 UTC, KrzysztofMoch approved these changes

2024-08-21 08:05 UTC, merged